spring:
  application:
    name: ${APP_NAME:wallet-service}


  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      timeout: 2000
  cloud:
    config:
      enabled: false

  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL:auto}
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        "[show_sql]": ${HIBERNATE_SHOW_SQL:false} 

  kafka:
    consumer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      group-id: ${KAFKA_GROUP_ID:wallet-service-group}
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: manual
      concurrency: ${KAFKA_CONSUMER_THREADS:3}
    producer:
      bootstrap-servers: ${KAFKA_SERVERS:localhost:9092}
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      

server:
  port: ${PORT:8000}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: 
      defaultZone: ${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
  instance:
    hostname: localhost
    non-secure-port: ${server.port}
    prefer-ip-address: true


logging:
  file.name: logs/wallet.log
  pattern:
    console: "${LOG_PATTERN:-%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n}"
    file: "${LOG_PATTERN:-%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n}"

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics


