server:
  port: ${CONFIG_SERVER_PORT}

spring:
  application:
    name: ${SPRING_APPLICATION_CONFIG_SERVER_NAME}

  cloud:
    config:
      server:
        git:
          uri: ${SPRING_CLOUD_CONFIG_SERVER_GIT_URI}
          clone-on-start: true
          timeout: 10
          force-pull: true
          skip-ssl-validation: true
          # If repo is private:
          # username: YOUR_GITHUB_USERNAME
          # password: YOUR_GITHUB_PAT
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVICE_URL}

logging:
  level:
    org:  
      springframework:
        cloud:
          config: DEBUG


  
